#!/bin/bash

. 00_define_database_environment.sh
export PGHOST=$MIMIC_POSTGRES_HOSTNAME
export PGPORT=$MIMIC_POSTGRES_PORT
export PGUSER=$MIMIC_POSTGRES_INITIAL_USER

psql -d postgres <<- EOSQL
    CREATE USER $MIMIC_POSTGRES_USER WITH PASSWORD '$MIMIC_POSTGRES_PASSWORD';
    CREATE DATABASE $MIMIC_POSTGRES_DATABASE OWNER $MIMIC_POSTGRES_USER;
    \c $MIMIC_POSTGRES_DATABASE;
    CREATE SCHEMA mimiciii;
        ALTER SCHEMA mimiciii OWNER TO $MIMIC_POSTGRES_USER;
EOSQL
